db:
  image: postgres

uwsgi:
  restart: always
  image: vanessa/sregistry
  volumes:
    - .:/code
    - ./static:/var/www/static
    - ./images:/var/www/images
    # uncomment for PAM auth
    #- /etc/passwd:/etc/passwd 
    #- /etc/shadow:/etc/shadow
  links:
    - rabbit
    - redis
    - db

nginx:
  restart: always
  image: vanessa/sregistry_nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
  volumes_from:
    - uwsgi
  links:
    - uwsgi
    - db

redis:
  restart: always
  image: redis:latest

rabbit:
  restart: always
  image: rabbitmq:latest

worker:
  image: vanessa/sregistry
  command: python /code/manage.py process_tasks 
#  command: celery worker -A shub.celery -Q default -n default@%h -B
  volumes:
    - .:/code
  volumes_from:
    - uwsgi
  links:
    - rabbit
    - redis
    - db
